### ISSUE TITLE
Random and Transparent 

### ISSUE THREAD

**Issue by N3rdP1um23** [orgordin/vuejs-avataaars#1]
Is there a way that I can set the avataaar to have no circle (transparent) and not have the shirt and skin and hat color be chosen randomly?

**Comment by orgordin** [comment]
Hi, I'm added the isCircle prop, you can try using props: 
:isCircle="false"
:clotheColor="'Blue01'"
:skinColor="'Light'"

You are more then welcome to make PR and collaborate :)
