### ISSUE TITLE
Random clotheType not rendering

### ISSUE THREAD

**Issue by cosmoslothnaut** [orgordin/vuejs-avataaars#5]
Occasionally my avatar would not render any clothing. I believe removing '|| Math.random() >= 0.7' in Avataaars.vue on line 70 fixed it for me.
Also, BlazerShirt was missing the shirt but changing clothes.js line 8 from 'path1' to 'BlazerShirt-path1' fixed the issue for me.

Thanks for your work!

**Comment by dekisha** [comment]
Hi @cosmoslothnaut I'm still having issues with that random clothe thing. I've updated Avataaars.vue as you suggested by removing that `|| Math.random() >= 0.7` but issue is still there. Have you done anything else in order to fix this? Thanks!

**Comment by cosmoslothnaut** [comment]
I thought that fixed it for me. I've made a few other changes so I can't say for certain anymore. 
Maybe its in one of these line
<template v-if="(clotheType === 'GraphicShirt')">
              <svg :style="cssVars" v-html="graphicType === 'random' ? getRandomChoice(GraphicShirtTypes) : GraphicShirtTypes[graphicType]" />
            </template>
            <template v-else>
              <svg v-html="clotheType === 'random' ? getRandomChoice(clothesType) : clothesType[clotheType]" />
            </template>

I could work on setting up a pull request though I've not done it before so it might take some time.
Let me know if that doesn't help and I can give it a try.

**Comment by dekisha** [comment]
@cosmoslothnaut sadly that didn't fix the issue for me :( You could try using https://www.npmjs.com/package/patch-package to make a patch first. That way you will see all the difference that you made with that package.

**Comment by cosmoslothnaut** [comment]
@dekisha I've created a pull request after reworking my changes a bit. I tested it a bit in my own app but let me know if it doesn't work for you.

**Comment by orgordin** [comment]
published the package with new version 4.0.0 
Thank you for your contribution!
