### ISSUE TITLE
TopType and HairColor don't sync for Hats

### ISSUE THREAD

**Issue by dhax** [orgordin/vuejs-avataaars#9]
The HairColor setting seems only to affect the TopType's color if TopType is not set to some "Hat" form but for Hair only. If set to a Hat type, then the HairColor setting has no affect on the Hat Color but is randomly chosen.

So should HairColor also set the Color of the chosen Hat from TopTypes? Otherwise there seems no way to save a color for a hat from TopTypes. Thanks.

**Comment by dhax** [comment]
OK I see now it's synced with the topColor attribute, which is missing in your README I guess. Thank you for this little gem!

**Comment by dhax** [comment]
also noticed in the README you write 'BeardMagestic', but it should be 'BeardMajestic'...

**Comment by orgordin** [comment]
Thanks for your comments.
